# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  # pip (Python)
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily

  # uv (Python)
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily

  # Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  # Docker Compose
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly

  # Devcontainers
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # git submodules
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
