.PHONY: all

all: build ## Default target: build the project

help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	@rm -rf target dist tmp .cache
	@find . -type f -name "*.DS_Store" -ls -delete
	@git fetch --prune
	@git gc --prune=now --aggressive

fmt: ## Run code formatters and linters
	yarn run check

build: ## Build the project
	yarn build

run: ## Run the project
	yarn start
