export {
  buildSocialUrl,
  convertGistToRawUrl,
  detectEntryType,
  getResumeSource,
  loadResumeData,
  normalizeEntries,
  normalizeListField,
} from "./resume";
export type {
  BulletEntry,
  CVData,
  EducationEntry,
  Entry,
  EntryKind,
  ExperienceEntry,
  LoadedResumeData,
  NormalEntry,
  OneLineEntry,
  PublicationEntry,
  RenderCVData,
  SocialNetwork,
  SocialNetworkName,
  TextEntry,
} from "./resume";
