name: Publish GitHub Pages

on:
  push:
    branches:
      - main
      - master
    tags:
      - v*

permissions: write-all

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build website with PDF
        env:
          VITE_WEBSITE_TITLE: Mai
          VITE_RESUME_FILE: example.yaml
          VITE_RESUME_PDF_PATH: resume.pdf
          VITE_ROOT_PATH: /${{ github.event.repository.name }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "<41898282+github-actions[bot]@users.noreply.github.com>"
          yarn install
          yarn build:all

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

      - name: Publish to GitHub Pages
        uses: actions/deploy-pages@v4
